### ISSUE TITLE
Logout muss auf /accounts/login/ weitergeleitet werden

### ISSUE THREAD

**Issue by mschwarz82** [innoq/seawatch_planner#31]
Nach einem Logout über den Logout-Button in der Navbar wird der Nutzer auf eine Admin-Seite weitergeleitet. Folgt er dort dem Link, um sich wieder einzuloggen, wird gelangt der Nutzer zum Admin-Login. Dort kann er sich nicht anmelden. Nutzer müssen sich über /accounts/login anmelden.

**Comment by hollesse** [comment]
Was hälst du von einer costum Log out page wo steht man wurde erfolgreich ausgeloggt und diese leitet nach 5 Sekunden auf die Index Seite weiter?

**Comment by mschwarz82** [comment]
Klingt gut!

**Comment by hollesse** [comment]
implemented with #32
