### ISSUE TITLE
[Crew-Anwendung] Positionsliste an Schiff hinterlegen

### ISSUE THREAD

**Issue by mschwarz82** [innoq/seawatch_planner#35]
Beim Anlegen eines Schiffes könnte neben dem Namen auch eine Liste von benötigten Positionen angelegt werden. Dann könnten später beim Assignment diese Positionen einfach gefüllt werden.

z.B.:
- 1x Kapitän
- 1x 1. Offizier
- 1x 2. Offizier
- 2x Koch
- 3x Arzt
- etc.

**Comment by hollesse** [comment]
umgesetzt mit #63

**Comment by hollesse** [comment]
#63

**Comment by hollesse** [comment]
implemented with #63
