### ISSUE TITLE
[Registierung] Kommentar pro Availabilty

### ISSUE THREAD

**Issue by hollesse** [innoq/seawatch_planner#39]
Es macht Sinn pro Availability einen Kommentar anlegen zu können. Gäbe es nur einen Kommentar für alle Availabilities könnte dieser Kommentar bei der Besetzung der Crew zu Verwirrung führen, da nicht erkennbar ist für welchen Zeitraum der Kommentar genau gilt, bzw. von anderen Zeiträumen die Rede ist, die hier nicht betrachtet werden.

**Comment by mschwarz82** [comment]
Hinzugefügt in 3b9ae4ede60cba345bb9c5ea54a6a1bae11be2b7
