### ISSUE TITLE
Anzeigen, welcher Nutzer gerade angemeldet ist

### ISSUE THREAD

**Issue by mschwarz82** [innoq/seawatch_planner#64]
Dadurch ist für den Benutzer einfacher ersichtlich, dass er angemeldet ist, und dass auch der richtige Nutzer angemeldet ist.

Beim debuggen hilft es auch, falls man mehrere Nutzer zum testen verwendet (z.B. bei der Rechte-Struktur)

**Comment by hollesse** [comment]
implemented in #65
