### ISSUE TITLE
[Crew-Anwendung] Wechsel von Assignments ermöglichen

### ISSUE THREAD

**Issue by mschwarz82** [innoq/seawatch_planner#69]
Problem:
Ich habe Manuel Müller als Koch eingeteilt.
Jetzt möchte ich einen Kapitän besetzen. Hier finde ich aber keinen. Manuel Müller könnte aber auch Kapitän sein. Diesen kann ich jedoch nicht mehr auswählen, weil er bereits als Koch eingeteilt wurde. Um diesen nun als Kapitän einteilen zu können, muss ich zunächst die Position Koch von der Crew löschen, damit Manuel Müller wieder frei ist. Dann muss ich ihn als Kapitän zuweisen. Anschließend muss ich wieder die Position Koch hinzufügen und dann eine andere Person als Koch einteilen.

Mögliche Lösungen:
1. In der Auswahl für eine Position werden auch bereits eingeplante Personen angezeigt und ggf. entsprechend markiert. Wird diese Person für eine neue Position besetzt, muss die alte Verknüpfung entfernt werden.
2. Es ist mögliche eine Zuweisung zu einer Position wieder zu entfernen, sodass die Person wieder für eine andere Position verfügbar ist.
3. ??? 

Aktuell ist mein Favorit die 1. Darf gerne diskutiert werden.

**Comment by hollesse** [comment]
Hierfür sollte am besten erst #19 umgesetzt werden.

**Comment by hollesse** [comment]
Ursprünglicher Inhalt ist aufgrund von Anpassungen aktuell Invalide.
