### ISSUE TITLE
[Crewing] Zuweisen einer Person - Requested und Approved Position

### ISSUE THREAD

**Issue by hollesse** [innoq/seawatch_planner#87]
Beim zuweisen einer Person soll ersichtlich sein, welche Position gewünscht und approved sind und welche lediglich approved sind. So soll für den SeaWatch Mitarbeiter ersichtlich sein, mit wem man ggf. Rücksprache halten müsse um diesen von der Positionseinteilung zu überzeugen.

**Comment by janmax** [comment]
Meinst du es reicht, wenn wir in der Assignmentliste einfach je eine Spalte für approved und requested positions haben? So hab ich das jetzt in #92 umgesetzt, und das passt auch ganz ok zu #82.

**Comment by hollesse** [comment]
Für den Anfang sollte das reichen. Wenns Nadja sich etwas anderes wünscht wird Sie es uns dann hoffentlich danach sagen...

**Comment by janmax** [comment]
Ok, bis dahin schließe ich das hier.
