### ISSUE TITLE
[Registration] Nationalität als Dropdown o. Auto-complete?

### ISSUE THREAD

**Issue by nadyes** [innoq/seawatch_planner#89]
Ich habe gerade gelesen, dass Drop-down-Menüs nicht nutzungsfreundlich sind - ich störe mich aber am Gedanken an "Deutsch", "Deutschland", "Germany", "German", "GER", "Grmany" und "Europa <3" im Freitextfeld.

**Comment by janmax** [comment]
Das stimmt (besonders für sehr große Menüs), imho ist es aber grundsätzlich zumutbar, wenn es nur an wenigen Stellen vorkommt. Die Alternative wäre ein Autocompletefeld, was aber nicht ohne Javascript funktioniert.

An dem Citizenship Feld kann auch ein Hilfetext stehen, welcher erklärt, dass dieses Feld mit der auf dem Ausweis angegebenen Nationalität übereinstimmen muss.

**Comment by janmax** [comment]
Hi @nadyes, mein Vorschlag wäre nun erstmal ein Feld zu nehmen, in dem mehrere Staatsbürgerschaften angegeben werden können (es gibt auch Menschen mit mehr als zwei Pässen). Auch das Feld für das Geburtsland wäre dann ein Dropdown. (Das ist auch bereits umgesetzt, mit deiner Zustimmung kann es sofort übernommen werden.)

Auto-complete wäre hier natürlich ideal. Braucht aber JavaScript, geht also evtl. nicht bei jedem. Das können wir immer noch in einem zweiten Schritt "oben drauf" bauen.
